# Electron RPA Application CI/CD Pipeline
name: Build and Deploy Electron RPA

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build-and-deploy:
    name: Build Electron RPA App
    uses: ./.github/workflows/ci.yml
    with:
      renderer-template: ''  # Use existing renderer
      distribution-channel: 'stable'
    permissions:
      contents: write
      id-token: write
      attestations: write
